#Assignment 2A
Name : Neelalohitha K.N. 
Batch : 3

# Backpropagation Step by Step
---
<center>![](https://hmkcode.github.io/images/ai/backpropagation.png)</center>

If you are building your own neural network, you will definitely need to understand how to train it. Backpropagation is a commonly used technique for training neural network. There are many resources explaining the technique, but this post will explain backpropagation with concrete example in a very detailed colorful steps.
<br>

## Overview
---
In this post, we will build a neural network with three layers:
<ul>
  <li><strong>Input</strong> layer with two inputs neurons</li>
  <li>One <strong>hidden</strong> layer with two neurons</li>
  <li><strong>Output</strong> layer with a single neuron</li>
</ul>

<center>![](https://hmkcode.github.io/images/ai/nn1.png)</center>

## Weights, weights, weights
___

Neural network training is about finding weights that minimize prediction error. We usually start our training with a set of randomly generated weights.Then, backpropagation is used to update the weights in an attempt to correctly map arbitrary inputs to outputs.

Our initial weights will be as following:<br>
```w1 = 0.07, w2 = 0.26, w3 = 0.13, w4 = 0.17, w5 = 0.18 and w6 = 0.24```
<br>

$$
\begin{bmatrix} 
  2  & 3 \\ 
  \end{bmatrix}
  .
  \begin{bmatrix}
  0.07 & 0.13 \\
  0.26 & 0.17
  \end{bmatrix}
  = 
  \begin{bmatrix}
  0.92 & 0.77 \\
  \end{bmatrix}
  .
  \begin{bmatrix}
  0.18 \\
  0.24
  \end{bmatrix}
  =
  0.3504
 $$ 
 
 ## Dataset
 ---
Our dataset has one sample with two inputs and one output.
<center>![](https://hmkcode.github.io/images/ai/bp_dataset.png)</center>
Our single sample is as following inputs=[2, 3] and output=[1].
<center>![](http://hmkcode.github.io/images/ai/bp_sample.png)</center>
 
 ## Forward Pass
 ---
 We will use given weights and inputs to predict the output. Inputs are multiplied by weights; the results are then passed forward to next layer.
 <br>
 
 ## Calculating Error
 ---
 Now, it’s time to find out how our network performed by calculating the difference between the actual output and predicted one. It’s clear that our network output, or **prediction**, is not even close to **actual output**. We can calculate the difference or the error as following.
 
## Reducing Error
---
Our main goal of the training is to reduce the **error** or the difference between **prediction** and **actual output**. Since **actual output** is constant, “not changing”, the only way to reduce the error is to change prediction value. The question now is, how to change **prediction** value?

By decomposing **prediction** into its basic elements we can find that **weights** are the variable elements affecting **prediction** value. In other words, in order to change **prediction** value, we need to change **weights** values.

 ![](http://hmkcode.github.io/images/ai/bp_prediction_elements.png) <br>
> The question now is **how to change\update the weights value so that the error is reduced?**
The answer is **Backpropagation!**


## Backpropagation
---
**Backpropagation**, short for “backward propagation of errors”, is a mechanism used to update the **weights** using [gradient descent](https://en.wikipedia.org/wiki/Gradient_descent). It calculates the gradient of the error function with respect to the neural network’s weights. The calculation proceeds backwards through the network.

> **Gradient descent** is an iterative optimization algorithm for finding the minimum of a function; in our case we want to minimize th error function. To find a local minimum of a function using gradient descent, one takes steps proportional to the negative of the gradient of the function at the current point.
<center>![bp_update_formula](https://hmkcode.github.io/images/ai/bp_update_formula.png)</center>

For example, to update `w6`, we take the current `w6` and subtract the partial derivative of **error** function with respect to `w6`. Optionally, we multiply the derivative of the **error** function by a selected number to make sure that the new updated **weight** is minimizing the **error** function; this number is called ***learning rate***.
<center> ![](https://hmkcode.github.io/images/ai/bp_w6_update.png) </center>

The derivation of the error function is evaluated by applying the chain rule as following
<center>![](https://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w6.png)</center>
So to update w6 we can apply the following formula
<center>
![](http://hmkcode.github.io/images/ai/bp_w6_update_closed_form.png)
</center>
Similarly, we can derive the update formula for `w5` and any other weights existing between the output and the hidden layer.

<center>![](http://hmkcode.github.io/images/ai/bp_w5_update_closed_form.png)
</center>
However, when moving backward to update ```w1, w2, w3 and w4``` existing between input and hidden layer, the partial derivative for the error function with respect to `w1`, for example, will be as following.
<center>![](http://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w1.png)</center>
We can find the update formula for the remaining weights ```w2, w3 and w4``` in the same way.
In summary, the update formulas for all weights will be as following:
<center>![](http://hmkcode.github.io/images/ai/bp_update_all_weights.png)</center>
We can rewrite the update formulas in matrices as following
<center>![](http://hmkcode.github.io/images/ai/bp_update_all_weights_matrix.png)</center>

##Backward Pass
---
Using derived formulas we can find the new **weights**.

> **Learning rate**: is a hyperparameter which means that we need to manually guess its value.

$$\bbox[2px,border:2px  dashed grey] {\Delta = 0.3504 - 1 = -0.6496} \leftarrow \boldsymbol{Delta} =Prediction - Actual $$ 

$$\bbox[2px,border:2px  dashed grey]{
a = 0.05
} \leftarrow \boldsymbol{Learning\space rate},we\space smartly \space guess\space this \space number$$

Now, using the new **weights** we will repeat the forward passed
$$\begin{bmatrix}
w5 \\
w6
\end{bmatrix} =
\begin{bmatrix}
0.18 \\
0.24
\end{bmatrix} - 0.05(-0.6496)\begin{bmatrix}
0.92 \\
0.77
\end{bmatrix} =
\begin{bmatrix}
0.18 \\
0.24
\end{bmatrix}
-
\begin{bmatrix}
-0.0299 \\
-0.0250 \\
\end{bmatrix}=
\begin{bmatrix}
0.2099\\
0.2650\\
\end{bmatrix}
$$

$$
\begin{bmatrix}
W1 & W3\\
W2 & W4\\
\end{bmatrix}
=
  \begin{bmatrix}
  0.07 & 0.13 \\
  0.26 & 0.17
  \end{bmatrix}
  - 0.05(-0.6496)\begin{bmatrix}
2 \\
3 \\
\end{bmatrix}
.
\begin{bmatrix}
0.18 &
0.24
\end{bmatrix}
=
  \begin{bmatrix}
  0.07 & 0.13 \\
  0.26 & 0.17
  \end{bmatrix}
  -
    \begin{bmatrix}
  -0.0117 & -0.0156 \\
  -0.0175 & -0.0234
  \end{bmatrix}
  =
    \begin{bmatrix}
  0.0817 & 0.1456 \\
  0.2775 & 0.1934\\
  \end{bmatrix}
$$
<br>
Now, using the new weights we will repeat the forward passed.
<br>

$$
\begin{bmatrix} 
  2  & 3 \\ 
  \end{bmatrix}
  .
 \begin{bmatrix}
  0.0817 & 0.1456 \\
  0.2775 & 0.1934\\
  \end{bmatrix}
  = 
  \begin{bmatrix}
  0.9959 & 0.8714 \\
  \end{bmatrix}
  .
\begin{bmatrix}
0.2099\\
0.2650\\
\end{bmatrix}
  =
  0.44
 $$ 
 <br>
 We can notice that the **prediction** `0.44` is a little bit closer to **actual output** than the previously predicted one `0.3504`. We can repeat the same process of backward and forward pass until **error** is close or equal to zero.

In [0]:
# Assignment 2B

import numpy as np

I = np.array([2,3]) #input
print('input',I)
out = [1] # output
print('out = ',out)

# Initial Weights
wa = np.array([[.07, 0.13], [0.26, 0.17]]) # weights w1,w2,w3,w4
wb = np.array([0.18, 0.24]) # weights w5,w6
print('wa = \n',wa)
print('wb = \n',wb)

#hidden layer
h = np.dot(I,wa)
print('hidden layer',h)

#Forward Pass-1
prediction_out = np.dot(h,wb)
print('prediction = ',prediction_out)


#Difference between actual output and prediction after 1st forward pass

delta_error = np.subtract(prediction_out,out)
print('Delta_error',delta_error)
a = 0.05 # Learning rate

#Weight(w5, w6) updation after 1st Backpropagation
wb_new = np.subtract(wb,a *delta_error *h)
print('wb after 1st backpropagation =\n',wb_new)

#Weight(w1, w2, w3, w4) updation after 1st backpropagation
wa_new =wa - a * delta_error * np.dot(I.reshape(2,1),wb.reshape(1,2)) # The array is reshaped to perform [2 X 1] X [1 X 2] matrix multiplication
print('wa after 1st backpropagation =')
print(wa_new)

#Hidden layer ,forward pass-2 
h = np.dot(I,wa_new)
print('hidden layer after 2nd Forward pass',h)

#Prediction after Forward Pass2 (and 1st backpropagation)
prediction_out = np.dot(h,wb_new)
print('prediction after 2nd Forward pass = ',prediction_out)


input [2 3]
out =  [1]
wa = 
 [[0.07 0.13]
 [0.26 0.17]]
wb = 
 [0.18 0.24]
hidden layer [0.92 0.77]
prediction =  0.3504
Delta_error [-0.6496]
wb after 1st backpropagation =
 [0.2098816 0.2650096]
wa after 1st backpropagation =
[[0.0816928 0.1455904]
 [0.2775392 0.1933856]]
hidden layer after 2nd Forward pass [0.9960032 0.8713376]
prediction after 2nd Forward pass =  0.43995557406207997


The same code is split into different cells to show the outputs at different stages 

In [0]:
import numpy as np


In [0]:
I = np.array([2,3]) #input
print('input = ',I)
out = [1] # output
print('out = ',out)

input =  [2 3]
out =  [1]


In [0]:
# Initial Weights
wa = np.array([[.07, 0.13], [0.26, 0.17]]) # weights w1,w2,w3,w4
wb = np.array([0.18, 0.24]) # weights w5,w6
print('wa =\n',wa)
print('wb =\n',wb)

wa =
 [[0.07 0.13]
 [0.26 0.17]]
wb =
 [0.18 0.24]


In [0]:
#hidden layer
h = np.dot(I,wa)
print('hidden layer',h)

hidden layer [0.92 0.77]


In [0]:
#Forward Pass-1
prediction_out = np.dot(h,wb)
print('prediction = ',prediction_out)

prediction =  0.3504


In [0]:
#Difference between actual output and prediction after 1st forward pass
delta_error = np.subtract(prediction_out,out)
print('Delta_error',delta_error)
a = 0.05 # Learning Rate

Delta_error [-0.6496]


In [0]:
#Weight(w5, w6) updation after 1st Backpropagation
wb_new = np.subtract(wb,a *delta_error *h)
print('wb after 1st backpropagation =\n',wb_new)

wb after 1st backpropagation =
 [0.2098816 0.2650096]


In [0]:
#Weight(w1, w2, w3, w4) updation after 1st backpropagation
wa_new =wa - a * delta_error * np.dot(I.reshape(2,1),wb.reshape(1,2)) # The array is reshaped to perform [2 X 1] X [1 X 2] matrix multiplication
print('wa after 1st backpropagation =')
print(wa_new)


wa after 1st backpropagation =
[[0.0816928 0.1455904]
 [0.2775392 0.1933856]]


In [0]:
#Hidden layer ,forward pass-2 
h = np.dot(I,wa_new)
print('hidden layer after 2nd Forward pass',h)

hidden layer after 2nd Forward pass [0.9960032 0.8713376]


In [0]:
#Prediction after Forward Pass2 (and 1st backpropagation)
prediction_out = np.dot(h,wb_new)
print('prediction after 2nd Forward pass = ',prediction_out)


prediction after 2nd Forward pass =  0.43995557406207997
